name: Linux OS(Ubuntu) Nim 2.2.4 compilation

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.4'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          sudo apt update
          sudo apt install libopengl-dev libgl1-mesa-dev libglfw3 libglfw3-dev
          sudo apt install libxcursor-dev libx11-dev libxext-dev libxinerama-dev libxi-dev
          sudo apt install ccache
          sudo ln -s /usr/bin/ccache /usr/local/bin/gcc
          sudo ln -s /usr/bin/ccache /usr/local/bin/g++
          lsb_release -a
      - run: |
          nimble build
          make
